baseURL = "https://andreaalessi.com/"
languageCode = "en-us"
title = "ResearchFlow"
theme = "PaperModX"


[params]
  author = "Andrea Alessi"
  showReadingTime = true
  showCodeCopyButtons = true
  custom_css = ["css/custom.css"]

[params.profileMode]
  enabled = false

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Collaborations"
    url = "/collaborations/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    name = "Observations"
    url = "/observations/"
    weight = 5
    
  [[menu.main]]
    name = "Useful Contents"
    url = "/usefulcontents/"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
